apiVersion: apps/v1
kind: Deployment
metadata:
  name: skys-api-app-dep
spec:
  selector:
    matchLabels:
      app: skys-api-app
  strategy:
    type: Recreate
  template:
    metadata:
      name: skys-api-app-pod
      labels:
        app: skys-api-app
    spec:
      containers:
        - name: skys-api-app
          image: skys-api:v1.0.0
          imagePullPolicy: Never
          volumeMounts:
            - name: skys-api-app
              mountPath: /var/www
            - name: skys-api-npm-log
              mountPath: /root/.npm/_logs
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: AWS_DEFAULT_REGION
              value: "ap-northeast-1"
            - name: AWS_DEFAULT_OUTPUT
              value: "json"
            - name: AWS_ACCESS_KEY_ID
              value: "test"
            - name: AWS_SECRET_ACCESS_KEY
              value: "test"
            - name: AWS_CLI_FILE_ENCODING
              value: "utf-8"
            - name: DATABASE_HOST
              value: "skys-dynamodb-svc"
            - name: DATABASE_PORT
              value: "8000"
            - name: APP_HOST
              value: "skys-api-app-svc"
            - name: APP_PORT
              value: "3000"
            - name: PM2_PUBLIC_KEY
              value: {{ .Values.container.pm2io.public_key }}
            - name: PM2_SECRET_KEY
              value: {{ .Values.container.pm2io.secret_key }}
      volumes:
        - name: skys-api-app
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}
            type: DirectoryOrCreate
        - name: skys-api-npm-log
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}/logs/npm
            type: DirectoryOrCreate
