apiVersion: v1
kind: Service
metadata:
  name: dev-skys-api-app-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    app: dev-skys-api-app
  ports:
    {{- range .Values.service.ports}}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      nodePort: {{ .nodePort }}
    {{- end}}