apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-skys-core-dep
spec:
  selector:
    matchLabels:
      app: dev-skys-core
  strategy:
    type: Recreate
  template:
    metadata:
      name: dev-skys-core-pod
      labels:
        app: dev-skys-core
    spec:
      containers:
        - name: dev-skys-core
          image: dev-skys-core
          imagePullPolicy: Never
          volumeMounts:
            - name: dev-skys-core
              mountPath: /var/www
            - name: dev-skys-core-npm-log
              mountPath: /root/.npm/_logs
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: AWS_DEFAULT_REGION
              value: "ap-northeast-1"
            - name: AWS_DEFAULT_OUTPUT
              value: "json"
            - name: AWS_ACCESS_KEY_ID
              value: "localstack"
            - name: AWS_SECRET_ACCESS_KEY
              value: "localstack"
            - name: AWS_CLI_FILE_ENCODING
              value: "utf-8"
            - name: DYNAMODB_HOST
              value: "localstack"
            - name: DYNAMODB_PORT
              value: "4566"
            - name: ELASTIC_SEARCH_HOST
              value: "dev-skys-es-http"
            - name: ELASTIC_SEARCH_PORT
              value: "9200"
            - name: ELASTIC_SEARCH_USER_NAME
              value: "elastic"
            - name: ELASTIC_SEARCH_PASSWORD
              value: {{ .Values.env.elasticsearch_password }}
      volumes:
        - name: dev-skys-core
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}/app
            type: DirectoryOrCreate
        - name: dev-skys-core-npm-log
          hostPath:
            path: {{ .Values.container.volume.project_root_path }}/app/logs/npm
            type: DirectoryOrCreate
