service:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30000
container:
  volume:
    project_root_path: default
env:
  elasticsearch_password: default