apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: dev-skys
spec:
  version: 8.13.0
  nodeSets:
    - name: default
      count: 1
      config:
        node.store.allow_mmap: false
