apiVersion: v1
kind: Service
metadata:
  name: dev-skys-elasticsearch-svc
spec:
  selector:
    app: dev-skys-elasticsearch
  ports:
    - name: http
      port: 9200
      targetPort: 9200
    - name: transport
      port: 9300
      targetPort: 9300
